site_name: IaaS JWT
repo_url: https://github.com/macewindubr/iaas-jwt
repo_name: macewindubr/iaas-jwt
edit_uri: tree/main/docs
theme:
  name: material
  language: pt-BR
  logo: assets/logo.png
  favicon: assets/logo.png

markdown_extensions: 
  - attr_list

extra_css:
  - stylesheets/extra.css

watch:
  - iaas_jwt

plugins:
- macros
- mkdocstrings:
    handlers:
      python:
        paths: [iaas_jwt]

extra:
  commands:
    run: iaas-jwt